import streamlit as st
import os

# Reemplaza 'GEMINI_API_KEY' por la clave que uses (puede ser GOOGLE_API_KEY o VERTEX_API_KEY)
os.environ['API_KEY_NAME'] = st.secrets["AIzaSyD-ygErYpn8nhJ9kAA9Rd3HJZewgVhoiYU"]